nodeLinker: pnpm

# https://github.com/typescript-eslint/typescript-eslint/issues/9224
packageExtensions:
  typescript-eslint@*:
    peerDependencies:
      eslint: '*'
  '@typescript-eslint/type-utils@*':
    peerDependencies:
      eslint: '*'
  '@typescript-eslint/utils@*':
    peerDependencies:
      typescript: '*'

yarnPath: .yarn/releases/yarn-4.5.0.cjs
