name: "Task"
description: "An Engineer Task Attached to a Story or Bug"
title: "(Scope) Title"
projects: ["alboe-development/4"]
type: "Task"
body:
  - type: markdown
    attributes:
        value: "# Task"

  - type: markdown
    attributes:
      value: "_An Engineer Task Attached to a Story or Bug._"

  - type: textarea
    id: definition
    attributes:
      label: "Definition"
      description: "The definition of this Task."
      placeholder: "In order to {resolution}, {definition}."
    validations:
      required: true
