name: Pull Request Action
run-name: Pull Request Action - ${{ github.actor }}


on:
  pull_request_target:
    branches:
      - main
    types: [opened, reopened, synchronize, labeled]


env:
  RID: ${{ github.run_id }}-${{ github.run_number }}


jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Validate Labels
        run: |
          HEAD_REPO=${{ github.event.pull_request.head.repo.full_name }}
          BASE_REPO=${{ github.event.pull_request.base.repo.full_name }}
          FROM_BASE=0; [ "$HEAD_REPO" == "$BASE_REPO" ] && FROM_BASE=1

          HAS_VALIDATED_LABEL=${{ contains(github.event.pull_request.labels.*.name, 'validated') || contains(github.event.workflow_run.labels.*.name, 'validated') || contains(github.event.label.name, 'validated') }}
          VALIDATED=0; [ "$HAS_VALIDATED_LABEL" == "true" ] && VALIDATED=1

          echo github.event

          echo from base $FROM_BASE
          echo validated $VALIDATED

          if [[ $FROM_BASE == 1 || $VALIDATED == 1 ]]
          then
            echo 'Pull request is validated, continuing.'
            exit 0
          else
            echo 'Pull request is not validated, exiting.'
            exit 1
          fi


  initialize:
    name: Initialize
    needs: [validate]
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          allow-unsafe-pr-checkout: true
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Initialize Node
        with: ./.github/actions/initialize-node


  build:
    name: Build
    needs: [validate, initialize, build]
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          allow-unsafe-pr-checkout: true
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Initialize Node
        uses: ./.github/actions/initialize-node

      - name: Build Project
        uses: ./.github/actions/build-project
        with:
          CACHE_ID: ${{ env.RID }}


  test-style:
    name: Test - Style
    needs: [validate, initialize, build]
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          allow-unsafe-pr-checkout: true
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Initialize Node
        uses: ./.github/actions/initialize-node

      - name: Build Project
        uses: ./.github/actions/build-project
        with:
          CACHE_ID: ${{ env.RID }}

      - name: Test
        run: pnpm @all test:style


  test-syntax:
    name: Test - Syntax
    needs: [validate, initialize, build]
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          allow-unsafe-pr-checkout: true
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Initialize Node
        uses: ./.github/actions/initialize-node

      - name: Build Project
        uses: ./.github/actions/build-project
        with:
          CACHE_ID: ${{ env.RID }}

      - name: Test
        run: pnpm @all test:syntax

  test-module:
    name: Test - Module
    needs: [validate, initialize, build]
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          allow-unsafe-pr-checkout: true
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Initialize Node
        uses: ./.github/actions/initialize-node

      - name: Build Project
        uses: ./.github/actions/build-project
        with:
          CACHE_ID: ${{ env.RID }}

      - name: Test
        run: pnpm @all test:module

  test-coverage:
    name: Test - Coverage
    needs: [validate, initialize, build]
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          allow-unsafe-pr-checkout: true
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Initialize Node
        uses: ./.github/actions/initialize-node

      - name: Build Project
        uses: ./.github/actions/build-project
        with:
          CACHE_ID: ${{ env.RID }}

      - name: Test
        run: pnpm @all test:coverage
